services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - MODULE_NAME=main
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
    networks:
      - esnet
    volumes:
      - .:/code
      - ./.env:/code/app/.env
      - ./fastapi:/code/app

  vite:
    build:
      context: ./SUPCHAT
      dockerfile: Dockerfile
    container_name: vite
    ports:
      - "5173:5173"
    networks:
      - esnet
    environment:
      - NODE_ENV=development

volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge